/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "calculadora.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static double *
_sumar_1 (operandoBasico  *argp, struct svc_req *rqstp)
{
	return (sumar_1_svc(*argp, rqstp));
}

static double *
_restar_1 (operandoBasico  *argp, struct svc_req *rqstp)
{
	return (restar_1_svc(*argp, rqstp));
}

static double *
_division_1 (operandoBasico  *argp, struct svc_req *rqstp)
{
	return (division_1_svc(*argp, rqstp));
}

static double *
_multiplicar_1 (operandoBasico  *argp, struct svc_req *rqstp)
{
	return (multiplicar_1_svc(*argp, rqstp));
}

static double *
_combinada_2 (combinada_2_argument *argp, struct svc_req *rqstp)
{
	return (combinada_2_svc(argp->arg1, argp->arg2, rqstp));
}

static vec *
_sumavector_3 (sumavector_3_argument *argp, struct svc_req *rqstp)
{
	return (sumavector_3_svc(argp->arg1, argp->arg2, rqstp));
}

static vec *
_restavector_3 (restavector_3_argument *argp, struct svc_req *rqstp)
{
	return (restavector_3_svc(argp->arg1, argp->arg2, rqstp));
}

static vec *
_multiplicarvector_3 (multiplicarvector_3_argument *argp, struct svc_req *rqstp)
{
	return (multiplicarvector_3_svc(argp->arg1, argp->arg2, rqstp));
}

static vec *
_dividirvector_3 (dividirvector_3_argument *argp, struct svc_req *rqstp)
{
	return (dividirvector_3_svc(argp->arg1, argp->arg2, rqstp));
}

static double *
_escalar_3 (escalar_3_argument *argp, struct svc_req *rqstp)
{
	return (escalar_3_svc(argp->arg1, argp->arg2, rqstp));
}

static vec *
_ecuacioncuadratica_4 (ecuacioncuadratica_4_argument *argp, struct svc_req *rqstp)
{
	return (ecuacioncuadratica_4_svc(argp->arg1, argp->arg2, argp->arg3, rqstp));
}

static void
calculadora_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		operandoBasico sumar_1_arg;
		operandoBasico restar_1_arg;
		operandoBasico division_1_arg;
		operandoBasico multiplicar_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case SUMAR:
		_xdr_argument = (xdrproc_t) xdr_operandoBasico;
		_xdr_result = (xdrproc_t) xdr_double;
		local = (char *(*)(char *, struct svc_req *)) _sumar_1;
		break;

	case RESTAR:
		_xdr_argument = (xdrproc_t) xdr_operandoBasico;
		_xdr_result = (xdrproc_t) xdr_double;
		local = (char *(*)(char *, struct svc_req *)) _restar_1;
		break;

	case DIVISION:
		_xdr_argument = (xdrproc_t) xdr_operandoBasico;
		_xdr_result = (xdrproc_t) xdr_double;
		local = (char *(*)(char *, struct svc_req *)) _division_1;
		break;

	case MULTIPLICAR:
		_xdr_argument = (xdrproc_t) xdr_operandoBasico;
		_xdr_result = (xdrproc_t) xdr_double;
		local = (char *(*)(char *, struct svc_req *)) _multiplicar_1;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

static void
calculadora_2(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		combinada_2_argument combinada_2_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case Combinada:
		_xdr_argument = (xdrproc_t) xdr_combinada_2_argument;
		_xdr_result = (xdrproc_t) xdr_double;
		local = (char *(*)(char *, struct svc_req *)) _combinada_2;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

static void
calculadora_3(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		sumavector_3_argument sumavector_3_arg;
		restavector_3_argument restavector_3_arg;
		multiplicarvector_3_argument multiplicarvector_3_arg;
		dividirvector_3_argument dividirvector_3_arg;
		escalar_3_argument escalar_3_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case SUMAVECTOR:
		_xdr_argument = (xdrproc_t) xdr_sumavector_3_argument;
		_xdr_result = (xdrproc_t) xdr_vec;
		local = (char *(*)(char *, struct svc_req *)) _sumavector_3;
		break;

	case RESTAVECTOR:
		_xdr_argument = (xdrproc_t) xdr_restavector_3_argument;
		_xdr_result = (xdrproc_t) xdr_vec;
		local = (char *(*)(char *, struct svc_req *)) _restavector_3;
		break;

	case MULTIPLICARVECTOR:
		_xdr_argument = (xdrproc_t) xdr_multiplicarvector_3_argument;
		_xdr_result = (xdrproc_t) xdr_vec;
		local = (char *(*)(char *, struct svc_req *)) _multiplicarvector_3;
		break;

	case DIVIDIRVECTOR:
		_xdr_argument = (xdrproc_t) xdr_dividirvector_3_argument;
		_xdr_result = (xdrproc_t) xdr_vec;
		local = (char *(*)(char *, struct svc_req *)) _dividirvector_3;
		break;

	case ESCALAR:
		_xdr_argument = (xdrproc_t) xdr_escalar_3_argument;
		_xdr_result = (xdrproc_t) xdr_double;
		local = (char *(*)(char *, struct svc_req *)) _escalar_3;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

static void
calculadora_4(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		ecuacioncuadratica_4_argument ecuacioncuadratica_4_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case ECUACIONCUADRATICA:
		_xdr_argument = (xdrproc_t) xdr_ecuacioncuadratica_4_argument;
		_xdr_result = (xdrproc_t) xdr_vec;
		local = (char *(*)(char *, struct svc_req *)) _ecuacioncuadratica_4;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (CALCULADORA, CV1);
	pmap_unset (CALCULADORA, CV2);
	pmap_unset (CALCULADORA, CV3);
	pmap_unset (CALCULADORA, CV4);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, CALCULADORA, CV1, calculadora_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (CALCULADORA, CV1, udp).");
		exit(1);
	}
	if (!svc_register(transp, CALCULADORA, CV2, calculadora_2, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (CALCULADORA, CV2, udp).");
		exit(1);
	}
	if (!svc_register(transp, CALCULADORA, CV3, calculadora_3, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (CALCULADORA, CV3, udp).");
		exit(1);
	}
	if (!svc_register(transp, CALCULADORA, CV4, calculadora_4, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (CALCULADORA, CV4, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, CALCULADORA, CV1, calculadora_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (CALCULADORA, CV1, tcp).");
		exit(1);
	}
	if (!svc_register(transp, CALCULADORA, CV2, calculadora_2, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (CALCULADORA, CV2, tcp).");
		exit(1);
	}
	if (!svc_register(transp, CALCULADORA, CV3, calculadora_3, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (CALCULADORA, CV3, tcp).");
		exit(1);
	}
	if (!svc_register(transp, CALCULADORA, CV4, calculadora_4, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (CALCULADORA, CV4, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
