/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "calculadora.h"

bool_t
xdr_operandoBasico (XDR *xdrs, operandoBasico *objp)
{
	register int32_t *buf;

	 if (!xdr_double (xdrs, &objp->a))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->b))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Num (XDR *xdrs, Num *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->numeros.numeros_val, (u_int *) &objp->numeros.numeros_len, ~0,
		sizeof (double), (xdrproc_t) xdr_double))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Ope (XDR *xdrs, Ope *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->operandos.operandos_val, (u_int *) &objp->operandos.operandos_len, ~0,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_vec (XDR *xdrs, vec *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->v.v_val, (u_int *) &objp->v.v_len, ~0,
		sizeof (double), (xdrproc_t) xdr_double))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_combinada_2_argument (XDR *xdrs, combinada_2_argument *objp)
{
	 if (!xdr_Num (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_Ope (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_sumavector_3_argument (XDR *xdrs, sumavector_3_argument *objp)
{
	 if (!xdr_vec (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_vec (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_restavector_3_argument (XDR *xdrs, restavector_3_argument *objp)
{
	 if (!xdr_vec (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_vec (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_multiplicarvector_3_argument (XDR *xdrs, multiplicarvector_3_argument *objp)
{
	 if (!xdr_vec (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_vec (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_dividirvector_3_argument (XDR *xdrs, dividirvector_3_argument *objp)
{
	 if (!xdr_vec (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_vec (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_escalar_3_argument (XDR *xdrs, escalar_3_argument *objp)
{
	 if (!xdr_vec (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_vec (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ecuacioncuadratica_4_argument (XDR *xdrs, ecuacioncuadratica_4_argument *objp)
{
	 if (!xdr_double (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->arg2))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->arg3))
		 return FALSE;
	return TRUE;
}
