/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"
#include "math.h"

void calculadora_1(char *host, operandoBasico op, char operacion)
{
	CLIENT *clnt;
	double *result_1;

#ifndef DEBUG
	clnt = clnt_create(host, CALCULADORA, CV1, "udp");
	if (clnt == NULL)
	{
		clnt_pcreateerror(host);
		exit(1);
	}
#endif /* DEBUG */

	switch (operacion)
	{
	case '+':
		result_1 = sumar_1(op, clnt);
		printf("El resultado de la operacion %f %c %f es: %f\n", op.a, operacion, op.b, *result_1);
		if (result_1 == (double *)NULL)
		{
			clnt_perror(clnt, "call failed");
		}
		break;

	case '-':
		result_1 = restar_1(op, clnt);
		printf("El resultado de la operacion %f %c %f es: %f\n", op.a, operacion, op.b, *result_1);
		if (result_1 == (double *)NULL)
		{
			clnt_perror(clnt, "call failed");
		}
		break;

	case '*':
	case 'x':
		result_1 = multiplicar_1(op, clnt);
		printf("El resultado de la operacion %f %c %f es: %f\n", op.a, operacion, op.b, *result_1);
		if (result_1 == (double *)NULL)
		{
			clnt_perror(clnt, "call failed");
		}
		break;

	case '/':
		result_1 = division_1(op, clnt);
		printf("El resultado de la operacion %f %c %f es: %f\n", op.a, operacion, op.b, *result_1);
		if (result_1 == (double *)NULL)
		{
			clnt_perror(clnt, "call failed");
		}
		break;

	default:
		printf("Operando no reconocido por la calculadora\n");
		exit(1);
		break;
	}

#ifndef DEBUG
	clnt_destroy(clnt);
#endif /* DEBUG */
}

void calculadora_2(char *host, Num nums, Ope ops)
{
	CLIENT *clnt;
	double *result_1;

#ifndef DEBUG
	clnt = clnt_create(host, CALCULADORA, CV2, "udp");
	if (clnt == NULL)
	{
		clnt_pcreateerror(host);
		exit(1);
	}

#endif /* DEBUG */

	result_1 = combinada_2(nums, ops, clnt);
	printf("El resultado de la operacion combinada es: %f\n", *result_1);
	if (result_1 == (double *)NULL)
	{
		clnt_perror(clnt, "call failed");
	}
#ifndef DEBUG
	clnt_destroy(clnt);
#endif /* DEBUG */
}

void calculadora_3(char *host, vec v1, vec v2, char op)
{
	CLIENT *clnt;
	vec *result_1;
	double *result_2;

#ifndef DEBUG
	clnt = clnt_create(host, CALCULADORA, CV3, "udp");
	if (clnt == NULL)
	{
		clnt_pcreateerror(host);
		exit(1);
	}
#endif /* DEBUG */

	switch (op)
	{
	case '+':
		result_1 = sumavector_3(v1, v2, clnt);
		printf("El vector resultante de la suma de los dos vectores es: \n");
		for (int i = 0; i < result_1->v.v_len; i++)
		{
			printf("%f \n", result_1->v.v_val[i]);
		}

		if (result_1 == (vec *)NULL)
		{
			clnt_perror(clnt, "call failed");
		}
		break;

	case '-':
		result_1 = restavector_3(v1, v2, clnt);
		printf("El vector resultante de la resta de los dos vectores es: \n");
		for (int i = 0; i < result_1->v.v_len; i++)
		{
			printf("%f \n", result_1->v.v_val[i]);
		}
		if (result_1 == (vec *)NULL)
		{
			clnt_perror(clnt, "call failed");
		}
		break;

	case '/':
		result_1 = dividirvector_3(v1, v2, clnt);
		printf("El vector resultante de la division de los dos vectores es: \n");
		for (int i = 0; i < result_1->v.v_len; i++)
		{
			printf("%f \n", result_1->v.v_val[i]);
		}
		if (result_1 == (vec *)NULL)
		{
			clnt_perror(clnt, "call failed");
		}
		break;

	case 'x':
		result_1 = multiplicarvector_3(v1, v2, clnt);
		printf("El vector resultante de la multiplicacion de los dos vectores es: \n");
		for (int i = 0; i < result_1->v.v_len; i++)
		{
			printf("%f \n", result_1->v.v_val[i]);
		}
		if (result_1 == (vec *)NULL)
		{
			clnt_perror(clnt, "call failed");
		}
		break;

	case 'e':
	case 'E':
		result_2 = escalar_3(v1, v2, clnt);
		printf("El producto escalar de los dos vectores es: %f \n", *result_2);

		if (result_1 == (vec *)NULL)
		{
			clnt_perror(clnt, "call failed");
		}
		break;

	default:
		printf("Operando no reconocido por la calculadora\n");
		exit(1);
		break;
	}

#ifndef DEBUG
	clnt_destroy(clnt);
#endif /* DEBUG */
}

void calculadora_4(char *host,double a, double b , double c)
{
	CLIENT *clnt;
	vec *result_1;
	

#ifndef DEBUG
	clnt = clnt_create(host, CALCULADORA, CV4, "udp");
	if (clnt == NULL)
	{
		clnt_pcreateerror(host);
		exit(1);
	}
#endif /* DEBUG */

	result_1 = ecuacioncuadratica_4(a, b, c, clnt);
	printf("El valor de x para la ecuación cuadrática es de x=%f y x=%f \n",result_1->v.v_val[0],result_1->v.v_val[1]);
	if (result_1 == (vec *)NULL)
	{
		clnt_perror(clnt, "call failed");
	}
#ifndef DEBUG
	clnt_destroy(clnt);
#endif /* DEBUG */
}

int main(int argc, char *argv[])
{
	char *host;

	operandoBasico oB;
	char *operando;

	int modo;
	Num num;
	Ope op;
	op.operandos.operandos_len = 0;
	num.numeros.numeros_len = 0;

	vec v1, v2;

	if (argc < 3)
	{
		printf("usage: %s server_host\n", argv[0]);
		exit(1);
	}

	host = argv[1];
	modo = atoi(argv[2]);

	if (modo == 1)
	{

		if (argc < 5)
		{
			printf("usage: %s server_host\n", argv[0]);
			exit(1);
		}
		oB.a = atof(argv[3]);
		operando = argv[4];
		oB.b = atof(argv[5]);
		calculadora_1(host, oB, *operando);
	}

	else if (modo == 2)
	{

		if (argc < 5)
		{
			printf("usage: %s server_host\n", argv[0]);
			exit(1);
		}

		for (int i = 3; i < argc; i++)
		{

			if (*argv[i] == '*' || *argv[i] == 'x' || *argv[i] == '+' || *argv[i] == '-' || *argv[i] == '/')
			{

				op.operandos.operandos_len++;
			}
			else
			{

				num.numeros.numeros_len++;
			}
		}

		op.operandos.operandos_val = (char *)malloc(op.operandos.operandos_len * sizeof(char));
		num.numeros.numeros_val = (double *)malloc(num.numeros.numeros_len * sizeof(double));

		int cont1 = 0, cont2 = 0;
		for (int i = 3; i < argc; i++)
		{

			if (*argv[i] == '*' || *argv[i] == 'x' || *argv[i] == '+' || *argv[i] == '-' || *argv[i] == '/')
			{
				op.operandos.operandos_val[cont1] = *argv[i];
				cont1++;
			}
			else
			{
				num.numeros.numeros_val[cont2] = atof(argv[i]);
				cont2++;
			}
		}

		calculadora_2(host, num, op);
	}

	else if (modo == 3)
	{
		if (argc < 3)
		{
			printf("usage: %s server_host\n", argv[0]);
			exit(1);
		}
		int tamano;

		do
		{

			printf("Introduzca el numero de elementos de los vectores \n");
			scanf("%d", &tamano);

		} while (tamano <= 0);

		v1.v.v_len = tamano;
		v2.v.v_len = tamano;

		v1.v.v_val = (double *)malloc(v1.v.v_len * sizeof(double));
		v2.v.v_val = (double *)malloc(v2.v.v_len * sizeof(double));

		for (int i = 0; i < v1.v.v_len; i++)
		{
			printf("Introduzca elemento %d del primer vector: \n", i);
			scanf("%lf", &v1.v.v_val[i]);
		}

		for (int i = 0; i < v2.v.v_len; i++)
		{
			printf("Introduzca elemento %d del segundo vector: \n", i);
			scanf("%lf", &v2.v.v_val[i]);
		}

		printf("Tenemos al vector: \n");

		for (int i = 0; i < v1.v.v_len; i++)
		{
			printf("%f ", v1.v.v_val[i]);
		}

		printf("\n\nY al vector: \n");

		for (int i = 0; i < v2.v.v_len; i++)
		{
			printf("%f ", v2.v.v_val[i]);
		}

		printf("\n \nQue operacion quiere realizar sobre estos vectores :\n Introduzca + para sumarlos.\n Introduzca - para restarlos.\n Introduzca x para multiplicarlos.\n Introduzca / para dividir.\n Introduzca e o E para producto escalar. \n");

		char op;
		scanf(" %c", &op);

		calculadora_3(host, v1, v2, op);
	}

	else if(modo==4)
	{

		double a,b,c;
		

		
		if (argc < 3)
		{
			printf("usage: %s server_host\n", argv[0]);
			exit(1);
		}

		
		
		printf("Introduzca los valores para resolver una ecuación cuadrática del tipo  ax^2 + b*x + c: \n");

		printf("Introduzca el valor de a o coeficiente lider: \n");
		scanf("%lf",&a);
		printf("Introduzca el valor de b o coeficiente lineal: \n");
		scanf("%lf",&b);
		printf("Introduzca el valor de c o término independiente: \n");
		scanf("%lf",&c);

		calculadora_4(host,a,b,c);

	}

	
	
	exit(0);
}
